[package]
name = "curvy_meta_registry"
version.workspace = true
edition.workspace = true

[dependencies]
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"

[dev-dependencies]
starknet.workspace = true
assert_macros.workspace = true
snforge_std.workspace = true

[scripts]
test = "snforge test"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true
