[workspace]
members = ["packages/account", "packages/meta_registry", "packages/announcer"]

[package]
name = "curvy_sn_prototype"
version.workspace = true

[workspace.package]
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.9.4"
scarb-version = "2.9.4"

[workspace.dependencies]
starknet = "2.9.4"
assert_macros = "2.9.4"
snforge_std = "0.37.0"

[dependencies]
starknet.workspace = true
curvy_account = { path = "packages/account" }
curvy_meta_registry = { path = "packages/meta_registry" }
curvy_announcer = { path = "packages/announcer" }

[dev-dependencies]
snforge_std = "0.37.0"
assert_macros = "2.9.4"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
