# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]                                         # Define a profile name
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7" # Url of the RPC provider
accounts-file = "./deployer.account.json"                        # Path to the file with the account data
account = "./deployer.account.json"
keystore = "./keystore.json"                                  # Path to the keystore file
wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer
